"""Curated ideal-resume data for ~15 popular roles across entry/mid/senior levels.

Each role has:
- id, name, level, category
- description
- core_skills (must-have)
- bonus_skills (nice-to-have)
- keywords (terms ATS systems look for)
- recommended_sections
- example_summary
- example_bullets (strong, quantified examples)
- project_ideas
- ideal_length_words
"""
from __future__ import annotations

ROLES = [
    {
        "id": "sde-entry",
        "name": "Software Development Engineer",
        "level": "entry",
        "category": "Engineering",
        "description": "Entry-level generalist who builds, tests, and ships features in a modern stack. Works under senior engineers to deliver well-tested code.",
        "core_skills": ["Python", "Java", "JavaScript", "Git", "SQL", "Data Structures", "Algorithms", "REST APIs"],
        "bonus_skills": ["Docker", "AWS", "React", "Node.js", "TypeScript", "CI/CD", "Linux", "PostgreSQL"],
        "keywords": ["microservices", "REST", "agile", "unit testing", "code review", "object-oriented", "scalable", "production"],
        "recommended_sections": ["summary", "education", "projects", "experience", "skills"],
        "example_summary": "Computer Science graduate with hands-on experience building full-stack web applications using Python, React, and PostgreSQL. Shipped 3 capstone projects end-to-end and contributed to open-source. Eager to learn from senior engineers in a fast-paced team.",
        "example_bullets": [
            "Built a REST API in FastAPI serving 5K daily requests with 99.9% uptime across 2 months",
            "Reduced API p95 latency by 35% by adding Redis caching and database query optimization",
            "Wrote 80+ unit tests achieving 92% coverage on a payment-processing module",
            "Mentored 2 junior interns on Git workflows and code review best practices",
        ],
        "project_ideas": [
            "URL shortener with Redis caching and analytics dashboard",
            "Real-time chat app using WebSockets and a relational DB",
            "CLI tool that automates a tedious task you do weekly",
        ],
        "ideal_length_words": [400, 700],
    },
    {
        "id": "frontend-entry",
        "name": "Frontend Developer",
        "level": "entry",
        "category": "Engineering",
        "description": "Builds responsive, accessible user interfaces with modern JavaScript frameworks. Focuses on UX, performance, and pixel-perfect implementation from Figma.",
        "core_skills": ["HTML", "CSS", "JavaScript", "React", "TypeScript", "Git", "Responsive Design", "REST APIs"],
        "bonus_skills": ["Next.js", "Tailwind CSS", "Redux", "Jest", "React Testing Library", "Webpack", "Vite", "Figma"],
        "keywords": ["accessibility", "WCAG", "responsive", "SPA", "component", "SSR", "performance", "Core Web Vitals"],
        "recommended_sections": ["summary", "projects", "experience", "skills", "education"],
        "example_summary": "Frontend developer with a strong design sense and 6 months of internship experience building React applications. Comfortable translating Figma designs into accessible, performant interfaces.",
        "example_bullets": [
            "Built a React dashboard used by 200+ internal users, reducing report-generation time by 70%",
            "Improved Lighthouse performance score from 62 to 94 by lazy-loading images and code-splitting routes",
            "Implemented WCAG 2.1 AA accessibility across 12 components, passing an external audit",
            "Created a reusable component library of 30+ buttons, inputs, and modals used across 4 projects",
        ],
        "project_ideas": [
            "Personal portfolio with dark mode and animated transitions",
            "Movie discovery app using TMDB API with infinite scroll",
            "Markdown editor with live preview and export to PDF",
        ],
        "ideal_length_words": [400, 700],
    },
    {
        "id": "backend-mid",
        "name": "Backend Developer",
        "level": "mid",
        "category": "Engineering",
        "description": "Designs and owns backend services, databases, and APIs. Balances performance, reliability, and developer experience. Mentors junior engineers.",
        "core_skills": ["Python", "Go", "Java", "PostgreSQL", "Redis", "Docker", "REST APIs", "System Design"],
        "bonus_skills": ["Kubernetes", "Kafka", "gRPC", "AWS", "Terraform", "GraphQL", "Elasticsearch", "Observability"],
        "keywords": ["microservices", "distributed systems", "scalability", "throughput", "latency", "idempotency", "event-driven", "load balancing"],
        "recommended_sections": ["summary", "experience", "projects", "skills", "education"],
        "example_summary": "Backend engineer with 4 years of experience designing distributed systems at scale. Led the migration of a monolith to microservices handling 50M daily events. Strong opinions on observability and graceful degradation.",
        "example_bullets": [
            "Architected an event-driven order pipeline in Kafka handling 10K events/sec with at-least-once delivery",
            "Reduced database read load by 60% by introducing a Redis caching layer with smart invalidation",
            "Owned the migration of 12 services from VMs to Kubernetes, cutting deploy time from 25 to 4 minutes",
            "Defined and enforced SLOs for 8 services; cut customer-impacting incidents by 40% in one quarter",
        ],
        "project_ideas": [
            "Open-source webhook delivery system with retries and dead-letter queues",
            "Distributed rate limiter using Redis and token buckets",
            "Time-series metrics store with downsampling",
        ],
        "ideal_length_words": [500, 900],
    },
    {
        "id": "fullstack-mid",
        "name": "Full-Stack Developer",
        "level": "mid",
        "category": "Engineering",
        "description": "Comfortable across the stack — React/Next.js on the front, Node/Python/Go on the back, with a working knowledge of databases and deployment.",
        "core_skills": ["React", "TypeScript", "Node.js", "Python", "PostgreSQL", "REST APIs", "Git", "Docker"],
        "bonus_skills": ["Next.js", "GraphQL", "Prisma", "AWS", "Vercel", "Tailwind", "Redis", "tRPC"],
        "keywords": ["end-to-end", "rapid prototyping", "MVP", "full lifecycle", "TypeScript", "serverless", "edge functions"],
        "recommended_sections": ["summary", "experience", "projects", "skills", "education"],
        "example_summary": "Full-stack engineer with 4 years at fast-moving startups. Shipped 5 production apps from zero to 100K users. Pragmatic about choosing boring technology when deadlines are tight.",
        "example_bullets": [
            "Shipped a SaaS analytics dashboard in 8 weeks that now serves 12K paying customers",
            "Reduced first-contentful paint by 50% by migrating from CRA to Next.js with ISR",
            "Built a multi-tenant auth system with row-level security used across 3 product lines",
        ],
        "project_ideas": [
            "Trello clone with real-time updates and drag-and-drop",
            "Budget tracker with bank-linking (Plaid sandbox)",
            "Job board with resume parsing and email alerts",
        ],
        "ideal_length_words": [500, 900],
    },
    {
        "id": "ds-entry",
        "name": "Data Scientist",
        "level": "entry",
        "category": "Data",
        "description": "Builds predictive models, runs experiments, and communicates insights to product and business stakeholders. Strong statistics + Python.",
        "core_skills": ["Python", "Pandas", "NumPy", "Scikit-learn", "SQL", "Statistics", "A/B Testing", "Data Visualization"],
        "bonus_skills": ["PyTorch", "TensorFlow", "Spark", "Airflow", "dbt", "Tableau", "R", "Bayesian Methods"],
        "keywords": ["experiment", "regression", "classification", "hypothesis testing", "feature engineering", "model evaluation", "cross-validation", "lift"],
        "recommended_sections": ["summary", "projects", "experience", "skills", "education"],
        "example_summary": "Data scientist with an MS in Statistics and 1 year of industry experience building churn and recommendation models. Published 2 analyses that drove measurable product changes.",
        "example_bullets": [
            "Built a churn-prediction model (XGBoost) that identified 70% of at-risk accounts 30 days in advance",
            "Ran 12 A/B tests on onboarding flows, lifting week-1 activation by 18%",
            "Designed an ETL pipeline in Airflow that processes 5M events daily into a feature store",
        ],
        "project_ideas": [
            "End-to-end churn prediction on the Telco dataset with a Streamlit demo",
            "Recommendation system using collaborative filtering on MovieLens",
            "Sentiment analysis dashboard for product reviews",
        ],
        "ideal_length_words": [400, 800],
    },
    {
        "id": "ml-mid",
        "name": "Machine Learning Engineer",
        "level": "mid",
        "category": "Data",
        "description": "Productionizes ML models: trains, evaluates, deploys, monitors, and maintains them at scale. Strong software engineering + ML fundamentals.",
        "core_skills": ["Python", "PyTorch", "TensorFlow", "Docker", "Kubernetes", "MLflow", "SQL", "Distributed Training"],
        "bonus_skills": ["Ray", "Triton", "CUDA", "Feast", "SageMaker", "Vertex AI", "Vector DBs", "LLMOps"],
        "keywords": ["MLOps", "model serving", "feature store", "online inference", "drift", "A/B", "low latency", "GPU"],
        "recommended_sections": ["summary", "experience", "projects", "skills", "education"],
        "example_summary": "ML engineer with 4 years of experience taking models from notebook to production. Shipped 6 models serving 100M+ predictions/day with sub-50ms p99 latency.",
        "example_bullets": [
            "Built a real-time fraud-detection pipeline (XGBoost + LSTM) catching 99.4% of fraudulent transactions",
            "Reduced inference cost by 70% by migrating from per-request GPU to batched CPU serving with distillation",
            "Designed a feature store on Redis that cut feature-computation time from minutes to milliseconds",
        ],
        "project_ideas": [
            "RAG chatbot with evaluation harness and online metrics",
            "Image classifier served via Triton on a free GPU",
            "Real-time recommendation API with online learning",
        ],
        "ideal_length_words": [500, 900],
    },
    {
        "id": "da-entry",
        "name": "Data Analyst",
        "level": "entry",
        "category": "Data",
        "description": "Turns raw data into clear insights for non-technical stakeholders. Strong SQL, dashboards, and storytelling.",
        "core_skills": ["SQL", "Excel", "Tableau", "Power BI", "Python", "Statistics", "Data Visualization", "Communication"],
        "bonus_skills": ["dbt", "Looker", "Snowflake", "BigQuery", "R", "Google Analytics", "Mixpanel", "Amplitude"],
        "keywords": ["dashboard", "KPI", "funnel", "cohort", "retention", "segmentation", "stakeholder", "insight"],
        "recommended_sections": ["summary", "experience", "projects", "skills", "education"],
        "example_summary": "Data analyst with a BS in Economics and 1 year of internship experience turning product usage data into actionable insights for growth and product teams.",
        "example_bullets": [
            "Built a self-serve Looker dashboard adopted by 25 stakeholders, replacing 8 ad-hoc weekly reports",
            "Identified a 15% drop in checkout conversion caused by a misconfigured payment provider",
            "Wrote 30+ SQL queries per week to support product, finance, and marketing decisions",
        ],
        "project_ideas": [
            "Public-data dashboard (e.g. NYC taxi, COVID) with Streamlit",
            "Cohort retention analysis on a real product (Spotify Wrapped-style)",
            "Marketing-attribution analysis with first-touch / last-touch models",
        ],
        "ideal_length_words": [400, 700],
    },
    {
        "id": "de-mid",
        "name": "Data Engineer",
        "level": "mid",
        "category": "Data",
        "description": "Designs and maintains data pipelines, warehouses, and infrastructure. Strong SQL, Python, distributed systems.",
        "core_skills": ["Python", "SQL", "Spark", "Airflow", "dbt", "Snowflake", "BigQuery", "Kafka"],
        "bonus_skills": ["Flink", "Databricks", "AWS Glue", "Terraform", "GCP", "DuckDB", "Polars", "Lakehouse"],
        "keywords": ["ETL", "ELT", "data pipeline", "data modeling", "partitioning", "orchestration", "data quality", "lineage"],
        "recommended_sections": ["summary", "experience", "projects", "skills", "education"],
        "example_summary": "Data engineer with 4 years building reliable pipelines at petabyte scale. Owned the migration from nightly cron jobs to orchestrated Airflow + dbt workflows serving 200+ dashboards.",
        "example_bullets": [
            "Rebuilt the analytics warehouse in dbt, reducing broken dashboards from 30 to 2",
            "Migrated 8TB of legacy ETL to Spark on Databricks, cutting nightly job time from 9 hours to 70 minutes",
            "Designed an event-capture pipeline (Kafka → S3 → Snowflake) ingesting 200M events/day",
        ],
        "project_ideas": [
            "Open-source GitHub events pipeline into a queryable warehouse",
            "Real-time crypto price tracker with Kafka and a live dashboard",
            "Data quality framework using Great Expectations",
        ],
        "ideal_length_words": [500, 900],
    },
    {
        "id": "devops-mid",
        "name": "DevOps / SRE Engineer",
        "level": "mid",
        "category": "Infrastructure",
        "description": "Owns CI/CD, infrastructure-as-code, observability, and on-call. Bridges development and operations.",
        "core_skills": ["Linux", "Docker", "Kubernetes", "Terraform", "AWS", "Git", "CI/CD", "Prometheus", "Grafana"],
        "bonus_skills": ["Ansible", "Pulumi", "Helm", "ArgoCD", "GitHub Actions", "Datadog", "PagerDuty", "Vault"],
        "keywords": ["SRE", "SLO", "incident response", "postmortem", "infrastructure as code", "GitOps", "observability", "on-call"],
        "recommended_sections": ["summary", "experience", "skills", "certifications"],
        "example_summary": "DevOps engineer with 5 years owning production infrastructure for B2B SaaS. Reduced incident MTTR by 60% through better observability and runbooks.",
        "example_bullets": [
            "Cut deploy time from 40 to 6 minutes by migrating Jenkins pipelines to GitHub Actions with parallel jobs",
            "Reduced cloud spend by $18K/month by rightsizing EC2 instances and introducing spot fleets",
            "Owned the SLO program; defined and tracked SLOs for 14 services with quarterly error budgets",
        ],
        "project_ideas": [
            "Self-hosted Kubernetes cluster on Raspberry Pi with GitOps",
            "End-to-end CI/CD pipeline for a sample microservice app",
            "Home observability stack with Prometheus, Grafana, and Loki",
        ],
        "ideal_length_words": [500, 900],
    },
    {
        "id": "cloud-mid",
        "name": "Cloud Engineer",
        "level": "mid",
        "category": "Infrastructure",
        "description": "Designs and operates AWS/GCP/Azure landing zones, networking, IAM, and cost-optimized infrastructure.",
        "core_skills": ["AWS", "Terraform", "Python", "Networking", "IAM", "VPC", "EC2", "S3", "Lambda"],
        "bonus_skills": ["GCP", "Azure", "Kubernetes", "CloudFormation", "CDK", "Crossplane", "FinOps", "Service Mesh"],
        "keywords": ["multi-AZ", "high availability", "disaster recovery", "cost optimization", "landing zone", "VPC peering", "Transit Gateway", "Well-Architected"],
        "recommended_sections": ["summary", "experience", "skills", "certifications"],
        "example_summary": "Cloud engineer with 4 years of AWS experience designing multi-account landing zones for fintech clients. AWS Solutions Architect Professional certified.",
        "example_bullets": [
            "Designed a 4-account AWS landing zone with centralized logging and IAM, replicated across 3 clients",
            "Migrated 40 services from EC2 to Fargate, cutting infrastructure cost by 35%",
            "Built Terraform modules used across 6 engineering teams, reducing boilerplate by 80%",
        ],
        "project_ideas": [
            "Static website deployed to S3 + CloudFront with Terraform",
            "Serverless URL shortener on Lambda + DynamoDB",
            "Cost dashboard scraping AWS Cost Explorer API",
        ],
        "ideal_length_words": [500, 900],
    },
    {
        "id": "android-entry",
        "name": "Android Developer",
        "level": "entry",
        "category": "Mobile",
        "description": "Builds native Android applications with Kotlin and Jetpack Compose. Familiar with the modern Android stack and Material 3.",
        "core_skills": ["Kotlin", "Jetpack Compose", "Android SDK", "MVVM", "Coroutines", "Flow", "REST APIs", "Git"],
        "bonus_skills": ["Room", "Hilt", "Retrofit", "Compose Navigation", "Espresso", "CI/CD", "Firebase", "Material 3"],
        "keywords": ["Material Design", "MVVM", "lifecycle", "navigation", "offline-first", "accessibility", "deep links", "Play Store"],
        "recommended_sections": ["summary", "projects", "experience", "skills", "education"],
        "example_summary": "Android developer with 2 published apps on the Play Store (10K+ installs combined). Strong in Kotlin, Jetpack Compose, and modern Android architecture.",
        "example_bullets": [
            "Built and shipped a Compose-based habit tracker with 5K+ downloads and 4.5★ rating",
            "Migrated a legacy XML-based app to Jetpack Compose, cutting APK size by 30%",
            "Implemented offline-first sync using Room + WorkManager with conflict resolution",
        ],
        "project_ideas": [
            "Expense tracker with Compose, Room, and a simple ML categorization",
            "Weather app using OpenWeatherMap and Compose animations",
            "Recipe app with offline storage and rich-text ingredients",
        ],
        "ideal_length_words": [400, 700],
    },
    {
        "id": "ios-entry",
        "name": "iOS Developer",
        "level": "entry",
        "category": "Mobile",
        "description": "Builds native iOS applications with Swift and SwiftUI. Familiar with the Apple ecosystem and App Store submission.",
        "core_skills": ["Swift", "SwiftUI", "UIKit", "Xcode", "Combine", "Core Data", "REST APIs", "Git"],
        "bonus_skills": ["Swift Concurrency", "Core Animation", "XCTest", "SwiftLint", "Fastlane", "Firebase", "ARKit", "App Clips"],
        "keywords": ["App Store", "TestFlight", "MVVM", "accessibility", "VoiceOver", "deep linking", "universal links", "privacy"],
        "recommended_sections": ["summary", "projects", "experience", "skills", "education"],
        "example_summary": "iOS developer with 1 published app on the App Store and strong SwiftUI chops. Comfortable with Combine, async/await, and modern Apple frameworks.",
        "example_bullets": [
            "Shipped a SwiftUI meditation app with 2K+ downloads and a 4.7★ rating",
            "Migrated a UIKit app to SwiftUI in 4 weeks with zero feature regressions",
            "Built a Core Data + CloudKit sync layer with conflict resolution used across 3 apps",
        ],
        "project_ideas": [
            "Habit tracker in SwiftUI with widgets and App Intents",
            "Personal finance app with CSV import and charts",
            "AR-based room-measurement prototype with ARKit",
        ],
        "ideal_length_words": [400, 700],
    },
    {
        "id": "pm-mid",
        "name": "Product Manager",
        "level": "mid",
        "category": "Product",
        "description": "Owns product vision, roadmap, and execution for a specific area. Partners with engineering, design, and GTM.",
        "core_skills": ["Roadmapping", "User Research", "A/B Testing", "SQL", "Analytics", "Stakeholder Management", "Prioritization", "PRD Writing"],
        "bonus_skills": ["Figma", "Mixpanel", "Amplitude", "Tableau", "Jira", "Linear", "Notion", "OKRs"],
        "keywords": ["north star metric", "jobs to be done", "user stories", "MVP", "go-to-market", "experimentation", "product-market fit", "OKRs"],
        "recommended_sections": ["summary", "experience", "skills", "education"],
        "example_summary": "Product manager with 4 years of B2B SaaS experience. Led the launch of a billing module that grew ARR by $3M in 12 months. Strong on data, ruthless on scope.",
        "example_bullets": [
            "Owned the launch of a usage-based billing module, growing ARR from $0 to $3M in 12 months",
            "Ran 14 experiments on the onboarding flow, lifting week-4 retention by 22%",
            "Defined and tracked 3 north-star metrics for the platform team across 6 squads",
        ],
        "project_ideas": [
            "Side project launched end-to-end with a small team — describe the journey",
            "Hypothetical product teardown of a public app with a strategic recommendation",
        ],
        "ideal_length_words": [500, 900],
    },
    {
        "id": "ux-entry",
        "name": "UX Designer",
        "level": "entry",
        "category": "Design",
        "description": "Designs intuitive, accessible interfaces grounded in user research. Strong on Figma, prototyping, and design systems.",
        "core_skills": ["Figma", "User Research", "Wireframing", "Prototyping", "Design Systems", "Usability Testing", "Information Architecture", "Accessibility"],
        "bonus_skills": ["After Effects", "Lottie", "HTML/CSS", "Framer", "Maze", "UserTesting", "Brand Design", "Motion"],
        "keywords": ["heuristic evaluation", "user journey", "persona", "wireframe", "mockup", "design system", "WCAG", "usability"],
        "recommended_sections": ["summary", "projects", "experience", "skills", "education"],
        "example_summary": "UX designer with a portfolio of 5 shipped case studies across mobile and web. Strong on accessibility (WCAG 2.1 AA) and design systems.",
        "example_bullets": [
            "Redesigned a healthcare portal, reducing task-completion time by 40% in usability tests with 12 patients",
            "Built a Figma component library of 60+ components adopted by 4 product squads",
            "Conducted 25+ user interviews that reshaped the onboarding flow for a fintech app",
        ],
        "project_ideas": [
            "Full case study of redesigning a public app with research, IA, and prototypes",
            "Design system from scratch with tokens, components, and documentation",
            "Accessibility audit of a popular website with concrete recommendations",
        ],
        "ideal_length_words": [400, 800],
    },
    {
        "id": "sec-entry",
        "name": "Cybersecurity Analyst",
        "level": "entry",
        "category": "Security",
        "description": "Monitors, investigates, and responds to security incidents. Familiar with SIEM, networking fundamentals, and common attack patterns.",
        "core_skills": ["Networking", "Linux", "SIEM", "Incident Response", "Threat Modeling", "Python", "Log Analysis", "OWASP Top 10"],
        "bonus_skills": ["Splunk", "CrowdStrike", "Burp Suite", "Wireshark", "Nmap", "Metasploit", "MITRE ATT&CK", "Cloud Security"],
        "keywords": ["SOC", "threat hunting", "vulnerability", "phishing", "malware", "forensics", "compliance", "penetration testing"],
        "recommended_sections": ["summary", "experience", "certifications", "projects", "skills", "education"],
        "example_summary": "Cybersecurity analyst with CompTIA Security+ and 1 year of SOC experience triaging alerts across endpoints, network, and cloud.",
        "example_bullets": [
            "Triaged 200+ alerts per week in Splunk, escalating 8 confirmed incidents in 3 months",
            "Built a Python script to auto-enrich phishing emails, cutting analyst response time by 50%",
            "Authored 3 runbooks adopted by the SOC for ransomware and credential-stuffing playbooks",
        ],
        "project_ideas": [
            "Home SOC lab with Wazuh + a vulnerable VM to attack",
            "CTF writeups (HackTheBox / TryHackMe) with methodology",
            "Threat-hunting notebook using public malware sandboxes",
        ],
        "ideal_length_words": [400, 800],
    },
]


def get_roles() -> list[dict]:
    return ROLES


def get_role(role_id: str) -> dict | None:
    return next((r for r in ROLES if r["id"] == role_id), None)
